# name: Build Next.js and Deploy to Azure

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: app

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18.x'

#       - name: Install dependencies and build
#         run: |
#           yarn install
#           yarn build

#       - name: Prepare deployment directory
#         run: |
#           mkdir site-deploy
#           cp -R .next site-deploy/
#           cp -R public site-deploy/
#           cp package.json site-deploy/
#           cp yarn.lock site-deploy/

#       - name: Package Next application for deployment
#         run: |
#           cd site-deploy
#           zip -qr next-app.zip ./*

#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v3
#         with:
#           name: next-app
#           path: app/site-deploy/next-app.zip

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'production'

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v3
#         with:
#           name: next-app

#       - name: Azure Login
#         uses: azure/login@v1
#         with:
#           creds: ${{ secrets.AZURE_CREDENTIALS }}

#       - name: 'Deploy to Azure Web App'
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'app-private-chatgpt-aydgnqft'
#           slot-name: 'production'
#           package: './next-app.zip'
#           startup-command: 'yarn install && yarn start'

#       - name: Cleanup
#         run: rm next-app.zip
