# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-private-chatgpt-aydgnqft

on:
  push:
    branches:
      - feature/rbac
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd ./src
          npm install
          npm run build --if-present
          npm run test --if-present
          cd ..

      - name: Copy standalone into the root
        run: cp -R ./src/.next/standalone ./site-deploy

      - name: Copy static into the .next folder
        run: cp -R ./src/.next/static ./site-deploy/.next/static

      - name: Copy Public folder
        run: cp -R ./src/public ./site-deploy/public

      - name: Package Next application
        run: |
          cd ./site-deploy
          zip app-code.zip ./* .next -qr      
          
      - name: Diagnostics
        run: |
          ls ./src
          ls ./src/.next
          ls ./site-deploy

      - name: Publish Next Application artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-code
          path: ./site-deploy/app-code.zip

  deploy:
    runs-on: ubuntu-latest

    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: app-code

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'app-private-chatgpt-aydgnqft'
          slot-name: 'Production'
          package: ${{ github.workspace }}/app-code.zip
