name: Deploy Next.js App to Azure

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
    paths:
    - 'app/**'
    - .github/workflows/nextjs.yaml
  pull_request:
    branches: [ main ]
    paths:
    - 'app/**'
    - .github/workflows/nextjs.yaml
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ./app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install SWC dependencies
        run: npm install @next/swc-linux-x64-gnu

      - name: Install dependencies, build and test
        run: |
          cd ./app
          npm install
          npm run build --if-present
          npm run test --if-present
          cd ..

      - name: Prepare deployment files
        run: |
          mkdir -p ./site-deploy/.next/static
          cp -R ./app/.next/standalone ./site-deploy
          cp -R ./app/.next/static ./site-deploy/.next/static
          cp -R ./app/public ./site-deploy/public
          cp -R ./app/node_modules ./site-deploy/node_modules

      - name: Package Next application for deployment
        run: |
          cd ./site-deploy
          zip app-code.zip ./* .next -qr      

      - name: List directories for diagnostics
        run: |
          ls ./app
          ls ./app/.next
          ls ./site-deploy

      - name: Upload packaged app as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-code
          path: ./site-deploy/app-code.zip

  deploy:
    runs-on: ubuntu-latest

    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-code

      - name: Construct AZURE_CREDENTIALS from individual secrets
        run: |
          echo AZURE_CREDENTIALS="{\"clientId\": \"${{ secrets.AZURE_CLIENT_ID }}\", \"clientSecret\": \"${{ secrets.AZURE_CLIENT_SECRET }}\", \"tenantId\": \"${{ secrets.AZURE_TENANT_ID }}\", \"subscriptionId\": \"${{ secrets.AZURE_SUBSCRIPTION_ID }}\"}" >> $GITHUB_ENV

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          slot-name: 'Production'
          package: ${{ github.workspace }}/app-code.zip
